parameters:
    canal_tp_scrum_board_it.jira.provider.class: CanalTP\ScrumBoardItBundle\IssuesProvider\JiraIssuesProvider

services:
    canal_tp_scrum_board_it.jira.provider:
        class: %canal_tp_scrum_board_it.jira.provider.class%
        arguments: [%jira_url%, %jira_login%, %jira_password%]
        calls:
            - [setSprint, [%sprint_id%]]
