services:
    canal_tp_scrum_board_it.service.manager:
        class: CanalTP\ScrumBoardItBundle\Service\ServiceManager
        arguments: [@service_container]
        calls:
            - [setServiceName, [%issues_service%]]
    canal_tp_scrum_board_it.jira.service:
        class: CanalTP\ScrumBoardItBundle\Service\JiraService
        calls:
            - [setOptions, [%jira%]]