# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                   # - jira_token_authenticator
                   # - github_token_authenticator
                    - sbi_authenticator
                    - visitor_authenticator
                entry_point: sbi_authenticator
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
            
    providers:
        webservice:
            id: webservice_user_provider
    
    encoders:
        ScrumBoardItBundle\Entity\User: bcrypt